print('What is your name?')
name=input()
print('Hello, '+name+'!')
print('How old are you, '+name+'?')
age=input()
print('You are '+age+'years old')
print('Where do you live, '+name+'?')
city=input()
print('You live in '+city+'')
print('Thanks a lot, '+name+'')